# run rabbitmq, redis

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - "5671:5671" # AMQPS port
      - "15672:15672"

  # redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
